### ISSUE TITLE
Adding @allcontributors to contributors leads to an infinite loop 😂

### ISSUE THREAD

**Issue by ValentinH** [all-contributors/all-contributors-bot#271] opened 2019-12-05 21:43 UTC
When using @allcontributors bot to add @allcontributors to the contributors, the bot adds comments infinitely!!! 😂

![image](https://user-images.githubusercontent.com/2678610/70276430-946bd800-17b0-11ea-953e-26c8077b605d.png)

Example: https://github.com/ricardo-ch/react-easy-crop/pull/79

How can I stop it? ^^

**Comment by ValentinH** [comment] 2019-12-05 22:20
I've managed to stop it by locking the PR conversation.

**Comment by kentcdodds** [comment] 2019-12-05 22:28
😂

**Comment by skywinder** [comment] 2019-12-07 06:04
Duplicate of https://github.com/all-contributors/all-contributors-bot/issues/266

**Closed** 2019-12-07 06:43 UTC
Labels: bug
